name: funcAgg3
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy
  - pandas
  - pytest=7.4.*
  - matplotlib=3.7.*
  - rasterio
  - rasterstats=0.19.*
  - geopandas=0.13.*
  - osmium-tool
  - tqdm
  - pyarrow=13.0.*
  - xlrd
  - pip
  - pip:
    - osmium
    - psutil
    - psycopg2
    - SQLAlchemy
    - GeoAlchemy2
    - palettable
    
